replicaCount: 3

image:
  repository: ghcr.io/danielye3005-a11y/monster-devops-app
  tag: latest

service:
  port: 80
  targetPort: 5000

ingress:
  host: monster.local

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
