apiVersion: v1
kind: Service

metadata:
  name: monster-app-service

spec:
  selector:
    app: monster-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: ClusterIP

